# Generated by Django 2.0.3 on 2018-03-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempC', models.FloatField()),
                ('tempF', models.FloatField()),
                ('creation_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
